# Site settings
title: Fabien Antoine
description: >
  Hi! I'm Fabien Antoine, a French entrepreneur who has created, is creating and will create
  digital projects. If you want to get more informations about them, you're in the right place.
baseurl: ""
url: "http://fantoine.com"

# Social settings
twitter_username: fabantoine
github_username:  fantoine
social_github: https://www.github.com/fantoine/
social_twitter: https://www.twitter.com/fabantoine
social_facebook: https://www.facebook.com/fantoinecom
social_googleplus: https://google.com/+FabienAntoine1
social_linkedin: http://www.linkedin.com/in/fabienantoine/
social_viadeo: http://www.viadeo.com/profile/0021jqw5dp8v8an1

# Build settings
markdown: kramdown

# More config
timezone: "Europe/Paris"

# Blog permalink
permalink: /blog/:categories/:slug

# Eclude them
exclude:
    - Gemfile
    - Gemfile.lock
    - bower.json
    - package.json
    - package-lock.json
    - gulpfile.js
    - README.md
    - node_modules
    - bower_components
