# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fabien Antoine
description: >
  Hi! I'm Fabien Antoine, a French entrepreneur who has created, is creating and will create
  digital projects. If you want to get more informations about them, you're in the right place.
baseurl: ""
url: "http://fantoine.com"

# Social settings
twitter_username: fabantoine
github_username:  fantoine
social_github: https://www.github.com/fantoine/
social_twitter: https://www.twitter.com/fabantoine
social_facebook: https://www.facebook.com/fantoinecom
social_googleplus: https://google.com/+FabienAntoine1
social_linkedin: http://www.linkedin.com/in/fabienantoine/
social_viadeo: http://www.viadeo.com/profile/0021jqw5dp8v8an1

# Build settings
markdown: kramdown

# More config
timezone: "Europe/Paris"

# Permalink
permalink: /blog/:categories/:slug
